import {component} from './Component'
import '../components/Ul'
import '../components/InputText'
import '../components/Form'
import '../components/Header'
import '../components/FilterList'
import '../components/Search'
import '../components/Issues'
import '../components/Goodreads'
import '../components/Console'
import '../components/Experiment'
component.initialise()
